### ISSUE TITLE
Cannot find module 'express'

### ISSUE THREAD

**Issue by farojos** [TransbankDevelopers/transbank-sdk-nodejs-webpay-example#4]
Para replicarlo: 
```
git clone https://github.com/TransbankDevelopers/transbank-sdk-nodejs-webpay-example
cd transbank-sdk-nodejs-webpay-example
docker-compose up --build
```

**Comment by gdespirito** [comment]
Gracias por el reporte. Acabo de subir un fix, que mañana debería aprobarse por el equipo. 
https://github.com/TransbankDevelopers/transbank-sdk-nodejs-webpay-example/pull/5

Si lo necesitas urgente, puedes usar ese branch para probarlo de momento, o usar la opción manual sin docker :)

**Comment by gdespirito** [comment]
Está aceptado el PR. Cerraré el issue ya que debería estar resuelto. Coméntame si se resuelve 👌

**Comment by farojos** [comment]
<img width="1156" alt="image" src="https://user-images.githubusercontent.com/7420935/77660126-b18f0700-6f57-11ea-9d92-3ac7cfa68166.png">
:)
