### ISSUE TITLE
Cannot load Soap Client, check your PEM certificates

### ISSUE THREAD

**Issue by cladveloper** [TransbankDevelopers/transbank-sdk-nodejs-webpay-example#7]
Al momento de iniciar el ejemplo me lanza el siguiente error:

Error: Cannot load Soap Client, check your PEM certificates | Could not find openssl on your system on this path: openssl
    at C:\Users\claudio.skdf\Desktop\GitHub\transbank-sdk-nodejs-webpay-example\node_modules\transbank-sdk\lib\webpay.js:43:15
(node:16224) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id:
6)
(node:16224) UnhandledPromiseRejectionWarning: Error: Cannot load Soap Client, check your PEM certificates | Could not find openssl on your system on this path: openssl

Tengo instalado OpenSSL en mi sistema, pero ni idea para hacerlo con Soap Client y que funcione bien con la App

**Comment by gdespirito** [comment]
Hola! Solo para confirmar ¿lo has intentado correr con Docker? Eso debería funcionar :)

¿Estás probando en Windows 10? Leí por ahí que quizás se soluciona instalando este paquete globalmente: npm install -g openssl

¿Me comentas si te funciona?

**Comment by cladveloper** [comment]
> Hola! Solo para confirmar ¿lo has intentado correr con Docker? Eso debería funcionar :)
> 
> ¿Estás probando en Windows 10? Leí por ahí que quizás se soluciona instalando este paquete globalmente: npm install -g openssl
> 
> ¿Me comentas si te funciona?

hola Gonzalo, gracias por la temprana respuesta. Si estoy con Windows 10, subí el repositorio a un VPS de prueba y funciona, así que el problema está en mi localhost. Instalaré el paquete que dices y te aviso, no he intentado correr con dockers.

Te aviso, muchas gracias!

**Comment by cladveloper** [comment]
> > Hola! Solo para confirmar ¿lo has intentado correr con Docker? Eso debería funcionar :)
> > ¿Estás probando en Windows 10? Leí por ahí que quizás se soluciona instalando este paquete globalmente: npm install -g openssl
> > ¿Me comentas si te funciona?
> 
> hola Gonzalo, gracias por la temprana respuesta. Si estoy con Windows 10, subí el repositorio a un VPS de prueba y funciona, así que el problema está en mi localhost. Instalaré el paquete que dices y te aviso, no he intentado correr con dockers.
> 
> Te aviso, muchas gracias!

funcionó instalando openssl de manera global!!! muchas gracias:D

**Comment by gdespirito** [comment]
Súper. Gracias por confirmar

**Comment by danieltadresu** [comment]
Hola! una duda, al generar la instancia del objeto transaction, presento el mismo error: **Cannot load Soap Cliente, chec your PEM certificates** 

const transaction = new Transbank.Webpay(
  Transbank.Configuration.forTestingWebpayPlusNormal()
).getNormalTransaction();

No puedo generar la Instancia, instalé el paquete npm install -g openssl pero el problema persiste.

Instalando el paquete, finalmente puedes ejecutarlo desde Windows 10? Si no puedo resolverlo, solo está la opción de correrlo mediante Docker?

Abrazos, gracias por sus comentarios

**Comment by gdespirito** [comment]
Hola @pizarrodani. No estoy seguro que dependencia es la que te falta para que funcione. Intenta correrlo en docker o en un VPS/Servidor con linux ó incluso en un mac y entiendo que te va a funcionar. Desconozco que cosa adicional hay que instalar en Windows para que funcione. (PD: podreias instalar el subsistema linux en windows 10 para probar también).

**Comment by pizarrodani** [comment]
Muchas gracias por la respuesta!! lo voy en Linux

**Comment by danieltadresu** [comment]
Funciona @gonzunigad Infinitas gracias !!

**Comment by gdespirito** [comment]
👌

**Comment by pizarrodani** [comment]
Hola Gonzalo nuevamente! te escribo ya que cloné el repo
transbank-sdk-nodejsy efectivamente me funciona perfect, estoy estudiando
la documentación en transbank para poder implementarlo en una prueba
personal y al seguir el ejemplo de la documentación, puedo pasarle la url
al action del form y el token al value del input de tipo hidden, genero el
archivo html, verifiqué que la url y el token se carguen en el action y en
el value y todo va correcto. Sin embargo, te quiero pedir ayuda ya que en
este punto presento inconvenientes, siguiendo la docu oficial de transbank,
doy click en el Botón y me redirecciona a la url de WebPay, sin embargo, me
señala que la Transacción no se pudo llevar a cabo, figura que "Ningún
cargo fue realizado en su tarjeta." Consulte el valor de la variable
amount, y está correcto, pero el problema persiste.
Es decir, no me permite ingresar los datos de la tarjeta como aparece en
los videos en Youtube.

La duda es, de qué manera puedo permitir que el cargo de la transacción,
almacenado en la variable amount, pueda ser entregado al Webpay? (En
términos más simples, de qué manera puedo resolver el error)

Muy agradecido nuevamente por tu respuesta Gonzalo

**Comment by danieltadresu** [comment]
Hola Gonzalo nuevamente! te escribo ya que cloné el repo transbank-sdk-nodejsy efectivamente me funciona perfect, estoy estudiando la documentación en transbank para poder implementarlo en una prueba personal y al seguir el ejemplo de la documentación, puedo pasarle la url al action del form y el token al value del input de tipo hidden, genero el archivo html, verifiqué que la url y el token se carguen en el action y en el value y todo va correcto. Sin embargo, te quiero pedir ayuda ya que en este punto presento inconvenientes, siguiendo la docu oficial de transbank, doy click en el Botón y me redirecciona a la url de WebPay, sin embargo, me señala que la Transacción no se pudo llevar a cabo, figura que "Ningún cargo fue realizado en su tarjeta." Consulte el valor de la variable amount, y está correcto, pero el problema persiste.
Es decir, no me permite ingresar los datos de la tarjeta como aparece en los videos en Youtube.

La duda es, de qué manera puedo permitir que el cargo de la transacción, almacenado en la variable amount, pueda ser entregado al Webpay? (En términos más simples, de qué manera puedo resolver el error)

Muy agradecido nuevamente por tu respuesta Gonzalo

**Comment by gdespirito** [comment]
Te recomiendo solicitar apoyo en slack : https://join-transbankdevelopers-slack.herokuapp.com/ para dejar este issue cerrado.

**Comment by Pujan92** [comment]
> Hi! Just to confirm, have you tried running it with Docker? That should work :)
> 
> Are you testing on Windows 10? I read out there that maybe it is fixed by installing this package globally: npm install -g openssl
> 
> Can you tell me if it works for you?

Hi,

I am facing the same issue in Windows 10 and have installed the openssl globally. Could you plz help me for it?
