### ISSUE TITLE
Problema con transacción en producción

### ISSUE THREAD

**Issue by niko20** [TransbankDevelopers/transbank-sdk-nodejs-webpay-example#8]
Al pasar el el proceso a producción entrega en todas las transacciones error 274, al parecer hay problemas con el metodo acknowledge en producción, pienso que debería existir la forma de poder ejecutarlo manual.

**Comment by gdespirito** [comment]
Hola @niko20 Gracias por reportar 😄 
¿Cual es el detalle del error? Digo, además del código 274. 
Todos los SDK oficiales tienen el acknowleddge para evitar errores, pero eso no ddebería generate problemas.

**Comment by ffiebig** [comment]
Cerrando por inactividad
